name: "CodeQL Analysis"

on:
  push:
    branches: [main]

jobs:
  analyze:
    name: Analyze Python Code with CodeQL
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write  # Needed to upload scan results

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild project
        uses: github/codeql-action/autobuild@v3

      # If your Python project needs manual build, use:
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: 3.11
      # - run: pip install -r requirements.txt

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
